import Navbar from "@/Components/Navbar";
import "./globals.css";
import { ThemeProvider } from "@/app/Context/ThemeContext";

export const metadata = {
  title: "Tayba Shaikh Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="transition-colors duration-500">
        <ThemeProvider>
          <Navbar />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
